// pch.h
#pragma once
#include <winrt/base.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.Devices.Bluetooth.h>
#include <winrt/Windows.Devices.Bluetooth.GenericAttributeProfile.h>
#include <winrt/Windows.Devices.Enumeration.h>
#include <winrt/Windows.Web.Syndication.h>
#include <winrt/Windows.Storage.Streams.h>
#include <iostream>
#include <cstdio>
#include <cstdint>
#include <string>
#include <winerror.h>
#include <set>